# Generated by Django 4.0.5 on 2022-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store', '0002_cart_customer_order_orderitem_cartitem_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
