# Generated by Django 4.0.5 on 2022-07-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_store', '0004_remove_customer_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
    ]
